name: Update discount & profit

on:
  schedule:
    - cron: "*/10 * * * *"   
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run updater
        run: python market_update.py

     
      - name: Debug changed files
        run: |
          echo "::group::git status (porcelain)"
          git status --porcelain
          echo "::endgroup::"

          echo "::group::ls -la docs"
          ls -la docs || true
          echo "::endgroup::"

          echo "::group::head -n 3 de CSVs"
          for f in docs/*.csv; do
            echo "--- $f ---"
            head -n 3 "$f" || true
          done
          echo "::endgroup::"

          echo "::group::hashes"
          which sha256sum && sha256sum docs/*.csv 2>/dev/null || true
          echo "::endgroup::"

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: refresh data [skip ci]"
          
          file_pattern: |
            docs/*.csv
            docs/last_run.json
            docs/stall_list.raw
            market_history.json
          
          add_options: "-A"
