name: Update market data

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas tabulate requests

      - name: Run discount (≥50%)
        run: python market_update.py

      - name: Build ALL SELL CSVs
        run: python build_all_sells.py

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: refresh data [skip ci]"
          file_pattern: |
            docs/discount_hits_ge_50pct.csv
            docs/last_run.json
            docs/stall_list.raw
            market_history.json
            docs/sales_all_today.csv
            docs/sales_all_today_enriched.csv
            docs/item_analysis_today.csv
            docs/stall_presence.csv
