name: Update market data

on:
  schedule:
    - cron: "*/15 * * * *"     # cada 30 min (UTC)
  workflow_dispatch: {}         # ejecutar manualmente

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas tabulate requests

      # Genera discount_hits_ge_50pct.csv y last_run.json
      - name: Build 50% OFF
        run: python market_update.py

      # ⬅️ NUEVO: genera todos los SELL y archivos de análisis en docs/
      - name: Build ALL SELL CSVs
        run: python build_all_sells.py

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: refresh data [skip ci]"
          file_pattern: |
            docs/discount_hits_ge_50pct.csv
            docs/last_run.json
            docs/stall_list.raw
            market_history.json
            docs/sales_all_today.csv
            docs/sales_all_today_enriched.csv
            docs/item_analysis_today.csv
            docs/stall_presence.csv
