name: Update market data

on:
  schedule:
    - cron: "*/30 * * * *"     # cada 30 min (UTC)
  workflow_dispatch: {}         # correr manualmente

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas tabulate requests

      # Genera discount_hits_ge_50pct.csv y last_run.json
      - name: Build 50% OFF
        run: python market_update.py

      # Genera todos los SELL + an치lisis y los deja en docs/
      - name: Build ALL SELL CSVs
        run: python build_all_sells.py

      # DEBUG: lista lo que qued칩 en docs/ y tama침os
      - name: List outputs
        run: |
          echo "== ls -la docs =="
          ls -la docs || true
          echo "== file sizes =="
          for f in docs/*; do [ -f "$f" ] && echo "$(stat -c%s "$f") bytes  $f"; done || true

      # DEBUG: sube docs/ como artifact para inspecci칩n
      - name: Upload docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-output
          path: docs/

      # Commit de todo lo generado
      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: refresh data [skip ci]"
          file_pattern: |
            docs/discount_hits_ge_50pct.csv
            docs/last_run.json
            docs/stall_list.raw
            market_history.json
            docs/sales_all_today.csv
            docs/sales_all_today_enriched.csv
            docs/item_analysis_today.csv
            docs/stall_presence.csv
